import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Link",
  description: "Generated by WB",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" type="image/png"></link>
      </head>
      <body>{children}</body>
    </html>
  );
}
